apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-calculator.fullname" . }}
  labels:
    {{- include "web-calculator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-calculator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "web-calculator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: username
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |-
                  health=$(curl -X POST -s -o /dev/null --write-out "%{http_code}" http://localhost:8080/api/v1/calculate --header 'Content-Type: application/json' --data '{ "expression":"2*2" }');
                  if [[ ${health} -ne 200 ]]; then exit 1; fi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |-
                  health=$(curl -X POST -s -o /dev/null --write-out "%{http_code}" http://localhost:8080/api/v1/calculate --header 'Content-Type: application/json' --data '{ "expression":"1+1" }');
                  if [[ ${health} -ne 200 ]]; then exit 1; fi
